language: python
jobs:
  include:
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.5
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.8
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install: pip install --upgrade pip
script:
  - tox -e repo-testwindows
