language: python
jobs:
  include:

    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis

    - name: "Python 3.7 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.7
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis


    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis


    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip install tox-travis

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.4
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip install tox-travis

    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip install tox-travis


    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.5
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH


    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.8
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install tox-travis
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

script: tox -e repo-test
install: pip install --upgrade pip
